import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import { options } from "./api/auth/[...nextauth]/options";
import { getServerSession } from "next-auth/next";
import AuthProvider from "./context/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(options);

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar user={session?.user} session={session}></Navbar>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
